# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gymgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    
    

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Gym")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 1200, 800))

        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setGeometry(QtCore.QRect(0, 0, 251, 801))
        self.navbar.setStyleSheet("background-color: #002877;\n""")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.navbar.setObjectName("navbar")

        self.content = QtWidgets.QLabel(self.centralwidget)
        self.content.setGeometry(QtCore.QRect(500, 200, 200, 200))
        self.content.setText("Main Menu")
        self.content.setScaledContents(True)
        self.content.setObjectName("content")
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.content.setFont(font)

        self.logo = QtWidgets.QLabel(self.navbar)
        self.logo.setGeometry(QtCore.QRect(40, 40, 171, 164))
        self.logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")

        self.InventoryButton = QtWidgets.QPushButton(self.navbar)
        self.InventoryButton.setGeometry(QtCore.QRect(1, 240, 251, 60))
        font = QtGui.QFont()
        self.InventoryButton.setStyleSheet("background-color: #002877;\n""color: white;\n""")
        self.InventoryButton.setObjectName("InventoryButton")


        self.RegistrationButton = QtWidgets.QPushButton(self.navbar)
        self.RegistrationButton.setGeometry(QtCore.QRect(1, 300, 251, 60))
        self.RegistrationButton.setStyleSheet("background-color: #002877;\n""color: white;\n""")
        self.RegistrationButton.setObjectName("RegistrationButton")

        self.SchedulingButton = QtWidgets.QPushButton(self.navbar)
        self.SchedulingButton.setEnabled(True)
        self.SchedulingButton.setGeometry(QtCore.QRect(1, 360, 251, 60))
        self.SchedulingButton.setStyleSheet("background-color: #002877;\n""color: white;\n""")
        self.SchedulingButton.setObjectName("SchedulingButton")

        self.ReportsButton = QtWidgets.QPushButton(self.navbar)
        self.ReportsButton.setGeometry(QtCore.QRect(1, 420, 251, 60))
        self.ReportsButton.setStyleSheet("background-color: #002877;\n""color: white;\n""")
        self.ReportsButton.setObjectName("ReportsButton")

        self.PaymentButton = QtWidgets.QPushButton(self.navbar)
        self.PaymentButton.setGeometry(QtCore.QRect(1, 480, 251, 60))
        self.PaymentButton.setStyleSheet("background-color: #002877;\n""color: white;\n""")
        self.PaymentButton.setObjectName("PaymentButton")

        self.HelpButton = QtWidgets.QPushButton(self.navbar)
        self.HelpButton.setGeometry(QtCore.QRect(1, 540, 251, 60))
        self.HelpButton.setStyleSheet("background-color: #002877;\n""color: white;\n""")
        self.HelpButton.setObjectName("HelpButton")

        self.AboutButton = QtWidgets.QPushButton(self.navbar)
        self.AboutButton.setGeometry(QtCore.QRect(1, 600, 251, 60))
        self.AboutButton.setStyleSheet("background-color: #002877;\n""color: white;\n""")
        self.AboutButton.setObjectName("AboutButton")

        self.LogoutButton = QtWidgets.QPushButton(self.navbar)
        self.LogoutButton.setGeometry(QtCore.QRect(1, 700, 251, 81))
        self.LogoutButton.setStyleSheet("color: white;\n""background-color: black;")
        self.LogoutButton.setObjectName("LOGOUT")
        MainWindow.setCentralWidget(self.centralwidget)

        # event listener
        self.InventoryButton.clicked.connect(lambda: self.clicked(1))
        self.RegistrationButton.clicked.connect(lambda: self.clicked(2))
        self.SchedulingButton.clicked.connect(lambda: self.clicked(3))
        self.ReportsButton.clicked.connect(lambda: self.clicked(4))
        self.PaymentButton.clicked.connect(lambda: self.clicked(5))
        self.HelpButton.clicked.connect(lambda: self.clicked(6))
        self.AboutButton.clicked.connect(lambda: self.clicked(7))
        self.LogoutButton.clicked.connect(lambda: self.clicked(8))

        self.Font()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def Font(self):

      buttons = {
            self.InventoryButton, self.RegistrationButton, self.SchedulingButton, 
            self.ReportsButton, self.PaymentButton, self.HelpButton, self.AboutButton,
            self.LogoutButton
      }

      font = QtGui.QFont()
      font.setFamily("Roboto")
      font.setPointSize(10)
      font.setBold(True)
      font.setWeight(75)
      font.setKerning(True)

      for i in buttons:
         i.setFont(font)


    def clicked(self, which):  
        if which == 1:
           self.content.setText("Inventory")
           self.update()
        if which == 2:
           self.content.setText("Registration")
           self.update()
        if which == 3:
           self.content.setText("Scheduling")
           self.update()
        if which == 4:
           self.content.setText("Reports")
           self.update()
        if which == 5:
           self.content.setText("Payment")
           self.update()
        if which == 6:
           self.content.setText("Help")
           self.update()
        if which == 7:
           self.content.setText("About")
           self.update()
        if which == 8:
           self.content.setText("Logout")
           self.update()

    def update(self):
        self.content.adjustSize()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InventoryButton.setText(_translate("MainWindow", "INVENTORY"))
        self.RegistrationButton.setText(_translate("MainWindow", "REGISTRATION"))
        self.SchedulingButton.setText(_translate("MainWindow", "SCHEDULING"))
        self.ReportsButton.setText(_translate("MainWindow", "REPORTS"))
        self.PaymentButton.setText(_translate("MainWindow", "PAYMENT"))
        self.HelpButton.setText(_translate("MainWindow", "HELP"))
        self.AboutButton.setText(_translate("MainWindow", "ABOUT"))
        self.LogoutButton.setText(_translate("MainWindow", "LOGOUT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
